name: Android CI
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Accept Licenses & Install NDK
        run: |
          yes | sdkmanager --licenses
          sdkmanager "ndk;29.0.13846066"

      - name: Grant permission
        run: chmod +x ./gradlew

      - name: Clean and Build APK
        run: ./gradlew clean assembleDebug
